---
# Configuration
# https://golangci-lint.run/usage/configuration/

version: "2"

linters:
  # https://golangci-lint.run/usage/configuration/#linters-configuration
  default: all

  # explicitly disabled linters
  disable:
    - containedctx
    - contextcheck
    - cyclop
    - depguard
    - errcheck
    - exhaustruct
    - exhaustive
    - forbidigo
    - gochecknoglobals  # no configuration options
    - lll
    - nilnil
    - nlreturn          # redundant with wsl
    - paralleltest
    - revive
    - tagalign
    - thelper
    - varnamelen
    - wrapcheck

  settings:
    cyclop:
      max-complexity: 12

    errcheck:
      exclude-functions:
        - fmt.Fprint
        - fmt.Fprintf
        - fmt.Fprintln
        - os.Close

    funlen:
      lines: 80
      statements: 60
      ignore-comments: true

    gomoddirectives:
      replace-allow-list:
        - github.com/slok/go-http-metrics

    gosec:
      excludes:
        - G104  # Errors unhandled
        - G304  # Potential file inclusion via variable (see https://github.com/golang/go/issues/67002)

    ireturn:
      allow:
        - error
        - empty
        - stdlib
        - generic
        - kong.Resolver 

    lll:
      line-length: 150

    recvcheck:
      exclusions:
        - "*.Map"

    tagliatelle:
      case:
        rules:
          json: snake
          yaml: snake

        overrides:
          - pkg: pkg/app/
            rules:
              json: camel

  exclusions:
    rules:
      - path: pkg/clui/
        linters:
          - forcetypeassert
          - funlen
          - ireturn

      - path: parser/
        linters:
          - staticcheck

      - path: oci/
        linters:
          - staticcheck

formatters:
  enable:
    - gofmt
    - gofumpt
    - goimports
